/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "awhptigbniwmkzffxcxu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3aHB0aWdibml3bWt6ZmZ4Y3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NjM0NjgsImV4cCI6MjA4NDEzOTQ2OH0.Ong6clISTsjXUsxg9ZkH4PhsS-8iZ2hgDWpkBW-DgpE"